name: Telemetry API - Infra Ops (Destroy / Import)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Selecciona la operación de infraestructura a ejecutar'
        required: true
        default: 'import'
        type: choice
        options:
          - import
          - destroy

jobs:
  infrastructure-operation:
    name: Run Terraform ${{ inputs.action }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Token con permisos para hacer commit del estado actualizado

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      # --- OPERACIÓN DE IMPORTACIÓN ---
      - name: Execute Terraform Import
        if: ${{ github.event.inputs.action == 'import' }}
        run: |
          echo "Sincronizando recursos existentes al estado local..."
          # Importamos ECR y el Rol de IAM para que Terraform los reconozca
          terraform import aws_ecr_repository.api_repo telemetry-api || true
          terraform import aws_iam_role.lambda_exec_role telemetry_lambda_role || true
        working-directory: ./infrastructure

      # --- OPERACIÓN DE DESTRUCCIÓN ---
      - name: Execute Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          echo "¡Destruyendo toda la infraestructura en AWS..."
          terraform destroy -auto-approve
        working-directory: ./infrastructure

      # Guardar los cambios del archivo .tfstate de vuelta en el repositorio
      - name: Commit State Changes Back to Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add infrastructure/terraform.tfstate || true
          git commit -m "chore: update terraform state after ${{ inputs.action }} [skip ci]" || echo "No state changes to commit"
          git push || echo "No changes to push"
        working-directory: ./infrastructure
